(self.webpackChunk_N_E = self.webpackChunk_N_E || []).push([
  [405],
  {
    8312: function (e, a, o) {
      (window.__NEXT_P = window.__NEXT_P || []).push([
        '/',
        function () {
          return o(4231);
        },
      ]);
    },
    4231: function (e, a, o) {
      'use strict';
      o.r(a),
        o.d(a, {
          default: function () {
            return H;
          },
        });
      var r = o(5893),
        n = o(1418),
        i = o.n(n),
        c = o(9008),
        m = o.n(c),
        l = o(2821);
      let t = [
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm HP',
          Damage: 76,
          Penetration: 15,
          'Pierce Level': 1,
          'Armor Damage': 5.2,
          'Velocity (m/s)': 884,
          Accuracy: '+1',
          'V.Recoil Control': 0,
          'H.Recoil Control': 0,
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm PS',
          Damage: 53,
          Penetration: 25,
          'Pierce Level': 2,
          'Armor Damage': 7.5,
          'Velocity (m/s)': 890,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm BP',
          Damage: 48,
          Penetration: 41,
          'Pierce Level': 4,
          'Armor Damage': 16.8,
          'Velocity (m/s)': 890,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm BS',
          Damage: 44,
          Penetration: 52,
          'Pierce Level': 5,
          'Armor Damage': 26,
          'Velocity (m/s)': 830,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm PP',
          Damage: 46,
          Penetration: 31,
          'Pierce Level': 3,
          'Armor Damage': 11.2,
          'Velocity (m/s)': 890,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm PRS',
          Damage: 59,
          Penetration: 11,
          'Pierce Level': 1,
          'Armor Damage': 4.9,
          'Velocity (m/s)': 890,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.45x39mm',
          Name: '5.45x39mm 7N10M F M',
          Damage: 50,
          Penetration: 35,
          'Pierce Level': 3,
          'Armor Damage': 10.6,
          'Velocity (m/s)': 880,
          Accuracy: '+51',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': -5,
        },
        {
          Caliber: '5.56x45mm',
          Name: '5.56x45mm HP Hunting',
          Damage: 72,
          Penetration: 14,
          'Pierce Level': 1,
          'Armor Damage': 5.1,
          'Velocity (m/s)': 947,
          Accuracy: '+1',
          'V.Recoil Control': '',
          'H.Recoil Control': '',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.56x45mm',
          Name: '5.56x45mm FMJ Hunting',
          Damage: 53,
          Penetration: 21,
          'Pierce Level': 2,
          'Armor Damage': 7.1,
          'Velocity (m/s)': 957,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.56x45mm',
          Name: '5.56x45mm M193',
          Damage: 52,
          Penetration: 12,
          'Pierce Level': 1,
          'Armor Damage': 7.1,
          'Velocity (m/s)': 957,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.56x45mm',
          Name: '5.56x45mm M855',
          Damage: 51,
          Penetration: 34,
          'Pierce Level': 3,
          'Armor Damage': 11.1,
          'Velocity (m/s)': 922,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.56x45mm',
          Name: '5.56x45mm M855A1',
          Damage: 49,
          Penetration: 40,
          'Pierce Level': 4,
          'Armor Damage': 17.5,
          'Velocity (m/s)': 945,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.56x45mm',
          Name: '5.56x45mm M995',
          Damage: 42,
          Penetration: 52,
          'Pierce Level': 5,
          'Armor Damage': 26.5,
          'Velocity (m/s)': 1013,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.8x42mm',
          Name: '5.8x42mm DBP87 Ammunition',
          Damage: 55,
          Penetration: 34,
          'Pierce Level': 3,
          'Armor Damage': 12.5,
          'Velocity (m/s)': 930,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.8x42mm',
          Name: '5.8x42mm DVP88 Ammunition',
          Damage: 51,
          Penetration: 44,
          'Pierce Level': 4,
          'Armor Damage': 19,
          'Velocity (m/s)': 870,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.8x42mm',
          Name: '5.8x42mm DVC12 Ammunition',
          Damage: 47,
          Penetration: 53,
          'Pierce Level': 5,
          'Armor Damage': 29,
          'Velocity (m/s)': 915,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm HP',
          Damage: 81,
          Penetration: 16,
          'Pierce Level': 1,
          'Armor Damage': 7,
          'Velocity (m/s)': 754,
          Accuracy: '+1',
          'V.Recoil Control': '',
          'H.Recoil Control': '',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm LP',
          Damage: 60,
          Penetration: 13,
          'Pierce Level': 1,
          'Armor Damage': 3.2,
          'Velocity (m/s)': 720,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm US',
          Damage: 55,
          Penetration: 27,
          'Pierce Level': 2,
          'Armor Damage': 9.2,
          'Velocity (m/s)': 300,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm T45M',
          Damage: 63,
          Penetration: 31,
          'Pierce Level': 3,
          'Armor Damage': 13.2,
          'Velocity (m/s)': 720,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm PS',
          Damage: 58,
          Penetration: 33,
          'Pierce Level': 3,
          'Armor Damage': 13.1,
          'Velocity (m/s)': 700,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm BP',
          Damage: 59,
          Penetration: 45,
          'Pierce Level': 4,
          'Armor Damage': 23.4,
          'Velocity (m/s)': 730,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x39mm',
          Name: '7.62x39mm AP',
          Damage: 49,
          Penetration: 54,
          'Pierce Level': 5,
          'Armor Damage': 32.4,
          'Velocity (m/s)': 730,
          Accuracy: '+1',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x51mm',
          Name: '7.62x51mm UN',
          Damage: 88,
          Penetration: 16,
          'Pierce Level': 1,
          'Armor Damage': 7.5,
          'Velocity (m/s)': 822,
          Accuracy: '+1',
          'V.Recoil Control': -2,
          'H.Recoil Control': -3,
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x51mm',
          Name: '7.62x51mm BPZ',
          Damage: 83,
          Penetration: 32,
          'Pierce Level': 3,
          'Armor Damage': 13.5,
          'Velocity (m/s)': 840,
          Accuracy: '+2',
          'V.Recoil Control': -3,
          'H.Recoil Control': -4,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x51mm',
          Name: '7.62x51mm M80',
          Damage: 81,
          Penetration: 42,
          'Pierce Level': 4,
          'Armor Damage': 21,
          'Velocity (m/s)': 833,
          Accuracy: '+3',
          'V.Recoil Control': -5,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x51mm',
          Name: '7.62x51mm M62',
          Damage: 71,
          Penetration: 53,
          'Pierce Level': 5,
          'Armor Damage': 28,
          'Velocity (m/s)': 816,
          Accuracy: '+4',
          'V.Recoil Control': -6,
          'H.Recoil Control': -6,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x51mm',
          Name: '7.62x51mm M61',
          Damage: 65,
          Penetration: 68,
          'Pierce Level': 6,
          'Armor Damage': 37.4,
          'Velocity (m/s)': 849,
          Accuracy: '+5',
          'V.Recoil Control': -7,
          'H.Recoil Control': -7,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x54mm',
          Name: '7.62x54mm LPS',
          Damage: 81,
          Penetration: 42,
          'Pierce Level': 4,
          'Armor Damage': 27,
          'Velocity (m/s)': 865,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x54mm',
          Name: '7.62x54mm T46M',
          Damage: 81,
          Penetration: 33,
          'Pierce Level': 3,
          'Armor Damage': 16.2,
          'Velocity (m/s)': 800,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x54mm',
          Name: '7.62x54mm SNB',
          Damage: 74,
          Penetration: 63,
          'Pierce Level': 6,
          'Armor Damage': 43.2,
          'Velocity (m/s)': 875,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x54mm',
          Name: '7.62x54mm 7BT1',
          Damage: 79,
          Penetration: 54,
          'Pierce Level': 5,
          'Armor Damage': 37.8,
          'Velocity (m/s)': 820,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x54mm',
          Name: '7.62x54mm 7N37',
          Damage: 71,
          Penetration: 71,
          'Pierce Level': 7,
          'Armor Damage': 54,
          'Velocity (m/s)': 785,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.338 Caliber',
          Name: '.338 UPZ',
          Damage: 118,
          Penetration: 42,
          'Pierce Level': 4,
          'Armor Damage': 29.5,
          'Velocity (m/s)': 849,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': 'High',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.338 Caliber',
          Name: '.338 FMJ',
          Damage: 102,
          Penetration: 54,
          'Pierce Level': 5,
          'Armor Damage': 41,
          'Velocity (m/s)': 900,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'High',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.338 Caliber',
          Name: '.338 AP',
          Damage: 94,
          Penetration: 64,
          'Pierce Level': 6,
          'Armor Damage': 55,
          'Velocity (m/s)': 849,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '12.7x99mm',
          Name: '12.7x99mm M2 M',
          Damage: 246,
          Penetration: 61,
          'Pierce Level': 6,
          'Armor Damage': 34.2,
          'Velocity (m/s)': 928,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.44 Caliber',
          Name: '.44 LFNP',
          Damage: 98,
          Penetration: 23,
          'Pierce Level': 2,
          'Armor Damage': 8,
          'Velocity (m/s)': 450,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.44 Caliber',
          Name: '.44 SJHP',
          Damage: 80,
          Penetration: 35,
          'Pierce Level': 3,
          'Armor Damage': 13,
          'Velocity (m/s)': 434,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.44 Caliber',
          Name: '.44 JSP',
          Damage: 72,
          Penetration: 42,
          'Pierce Level': 4,
          'Armor Damage': 18,
          'Velocity (m/s)': 450,
          Accuracy: '+3',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.45 Caliber',
          Name: '.45 HS',
          Damage: 58,
          Penetration: 11,
          'Pierce Level': 1,
          'Armor Damage': 2.9,
          'Velocity (m/s)': 274,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.45 Caliber',
          Name: '.45 FMJ',
          Damage: 54,
          Penetration: 19,
          'Pierce Level': 1,
          'Armor Damage': 5.6,
          'Velocity (m/s)': 285,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '.45 Caliber',
          Name: '.45 AP',
          Damage: 49,
          Penetration: 32,
          'Pierce Level': 3,
          'Armor Damage': 9.2,
          'Velocity (m/s)': 299,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x25mm',
          Name: '7.62x25mm PT',
          Damage: 55,
          Penetration: 19,
          'Pierce Level': 1,
          'Armor Damage': 5.9,
          'Velocity (m/s)': 415,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x25mm',
          Name: '7.62x25mm Pst',
          Damage: 50,
          Penetration: 22,
          'Pierce Level': 2,
          'Armor Damage': 10.3,
          'Velocity (m/s)': 430,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x25mm',
          Name: '7.62x25mm LRN',
          Damage: 64,
          Penetration: 9,
          'Pierce Level': 0,
          'Armor Damage': 2.1,
          'Velocity (m/s)': 375,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '7.62x25mm',
          Name: '7.62x25mm AKBS',
          Damage: 58,
          Penetration: 13,
          'Pierce Level': 1,
          'Armor Damage': 4.5,
          'Velocity (m/s)': 425,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x19mm',
          Name: '9x19mm PSO',
          Damage: 54,
          Penetration: 15,
          'Pierce Level': 1,
          'Armor Damage': 5.8,
          'Velocity (m/s)': 340,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x19mm',
          Name: '9x19mm Pst',
          Damage: 50,
          Penetration: 20,
          'Pierce Level': 2,
          'Armor Damage': 7,
          'Velocity (m/s)': 457,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x19mm',
          Name: '9x19mm AP6.3',
          Damage: 48,
          Penetration: 30,
          'Pierce Level': 3,
          'Armor Damage': 12,
          'Velocity (m/s)': 392,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x19mm',
          Name: '9x19mm DumDum',
          Damage: 77,
          Penetration: 4,
          'Pierce Level': 0,
          'Armor Damage': 1.2,
          'Velocity (m/s)': 381,
          Accuracy: '+1',
          'V.Recoil Control': '',
          'H.Recoil Control': '',
          'Wound Chance': 'High',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x19mm',
          Name: '9x19mm 7N30 F M',
          Damage: 49,
          Penetration: 35,
          'Pierce Level': 3,
          'Armor Damage': 12,
          'Velocity (m/s)': 445,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': -5,
        },
        {
          Caliber: '9x19mm',
          Name: '9x19mm 7N31',
          Damage: 47,
          Penetration: 40,
          'Pierce Level': 4,
          'Armor Damage': 19.2,
          'Velocity (m/s)': 600,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Type 5 Buckshot',
          Damage: '36x8 (288)',
          Penetration: 1,
          'Pierce Level': 0,
          'Armor Damage': 1,
          'Velocity (m/s)': 330,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'High',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Type 7 Buckshot',
          Damage: '37x8 (296)',
          Penetration: 12,
          'Pierce Level': 1,
          'Armor Damage': 1,
          'Velocity (m/s)': 415,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Type 8 Buckshot',
          Damage: '43*8 (344)',
          Penetration: 4,
          'Pierce Level': 0,
          'Armor Damage': 1,
          'Velocity (m/s)': 385,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Flechette Buckshot',
          Damage: '27*8 (216)',
          Penetration: 33,
          'Pierce Level': 3,
          'Armor Damage': 2,
          'Velocity (m/s)': 320,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Dual Shell',
          Damage: '86*2 (172)',
          Penetration: 19,
          'Pierce Level': 1,
          'Armor Damage': 3,
          'Velocity (m/s)': 415,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': 'Medium',
          'Extra Range': '+10m',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Led Slug',
          Damage: 178,
          Penetration: 18,
          'Pierce Level': 1,
          'Armor Damage': 9.4,
          'Velocity (m/s)': 370,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': 'Low',
          'Extra Range': '+10m',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Grizzly Slug',
          Damage: 187,
          Penetration: 11,
          'Pierce Level': 1,
          'Armor Damage': 7.7,
          'Velocity (m/s)': 390,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Medium',
          'Extra Range': '+10m',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm RIP Slug',
          Damage: 274,
          Penetration: 3,
          'Pierce Level': 0,
          'Armor Damage': 14.8,
          'Velocity (m/s)': 410,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'High',
          'Extra Range': '+10m',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm GT Slug',
          Damage: 201,
          Penetration: 27,
          'Pierce Level': 2,
          'Armor Damage': 14.8,
          'Velocity (m/s)': 410,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': 'Low',
          'Extra Range': '+10m',
          'Stamina Drain': '',
        },
        {
          Caliber: '12x70mm',
          Name: '12x70mm Armor-Piercing Slug',
          Damage: 172,
          Penetration: 35,
          'Pierce Level': 3,
          'Armor Damage': 15.4,
          'Velocity (m/s)': 510,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '+10m',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.7x28mm',
          Name: '5.7x28mm R37.F',
          Damage: 81,
          Penetration: 5,
          'Pierce Level': 0,
          'Armor Damage': 3.9,
          'Velocity (m/s)': 729,
          Accuracy: '+1',
          'V.Recoil Control': '',
          'H.Recoil Control': '',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.7x28mm',
          Name: '5.7x28mm SS197SR',
          Damage: 62,
          Penetration: 22,
          'Pierce Level': 2,
          'Armor Damage': 9.4,
          'Velocity (m/s)': 594,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.7x28mm',
          Name: '5.7x28mm SS190',
          Damage: 49,
          Penetration: 41,
          'Pierce Level': 4,
          'Armor Damage': 17.6,
          'Velocity (m/s)': 716,
          Accuracy: '+5',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.7x28mm',
          Name: '5.7x28mm R37.X',
          Damage: 74,
          Penetration: 15,
          'Pierce Level': 1,
          'Armor Damage': 6.3,
          'Velocity (m/s)': 724,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': 'Medium',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.7x28mm',
          Name: '5.7x28mm L191',
          Damage: 58,
          Penetration: 32,
          'Pierce Level': 3,
          'Armor Damage': 11.4,
          'Velocity (m/s)': 716,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '5.7x28mm',
          Name: '5.7x28mm SS198',
          Damage: 46,
          Penetration: 53,
          'Pierce Level': 5,
          'Armor Damage': 22.8,
          'Velocity (m/s)': 792,
          Accuracy: '+1',
          'V.Recoil Control': -3,
          'H.Recoil Control': -5,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x39mm',
          Name: '9x39mm SP5',
          Damage: 67,
          Penetration: 33,
          'Pierce Level': 3,
          'Armor Damage': 10.6,
          'Velocity (m/s)': 290,
          Accuracy: '+1',
          'V.Recoil Control': '+2',
          'H.Recoil Control': '+4',
          'Wound Chance': 'Low',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x39mm',
          Name: '9x39mm SP6',
          Damage: 57,
          Penetration: 41,
          'Pierce Level': 4,
          'Armor Damage': 18,
          'Velocity (m/s)': 305,
          Accuracy: '+2',
          'V.Recoil Control': '+1',
          'H.Recoil Control': '+2',
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x39mm',
          Name: '9x39mm 7N9',
          Damage: 60,
          Penetration: 47,
          'Pierce Level': 4,
          'Armor Damage': 12.6,
          'Velocity (m/s)': 310,
          Accuracy: '+3',
          'V.Recoil Control': -1,
          'H.Recoil Control': -2,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
        {
          Caliber: '9x39mm',
          Name: '9x39mm 7N12',
          Damage: 55,
          Penetration: 50,
          'Pierce Level': 5,
          'Armor Damage': 21.7,
          'Velocity (m/s)': 295,
          Accuracy: '+4',
          'V.Recoil Control': -2,
          'H.Recoil Control': -4,
          'Wound Chance': '',
          'Extra Range': '',
          'Stamina Drain': '',
        },
      ];
      var x = o(3558),
        g = o(7747),
        C = o(7239),
        s = o(8783),
        u = o(4e3),
        d = o(8948),
        D = o(2215),
        R = o(8087),
        h = o(7294);
      let A = (e, a) => {
          if ('' === e) return;
          let o = a ? -Number(e) : Number(e);
          return o > 0
            ? '#4cf057'
            : o < 0
            ? '#cf0b04'
            : 0 === o
            ? 'gray.500'
            : void 0;
        },
        y = (e) =>
          0 === e
            ? 'gray.300'
            : e
            ? '' === e
              ? 'vulcan.900'
              : (null == e ? void 0 : e.toString().includes('+'))
              ? '#4cf057'
              : (null == e ? void 0 : e.toString().includes('-'))
              ? '#cf0b04'
              : (
                  null == e
                    ? void 0
                    : e.toString().toLowerCase().includes('medium')
                )
              ? 'orange'
              : (
                  null == e
                    ? void 0
                    : e.toString().toLowerCase().includes('low')
                )
              ? '#cf0b04'
              : (
                  null == e
                    ? void 0
                    : e.toString().toLowerCase().includes('high')
                )
              ? '#4cf057'
              : 'tarkovYellow.100'
            : '';
      var P = o(4071),
        b = o(7334),
        V = o(3717),
        S = o(2185),
        p = o(4292),
        v = o(5028),
        j = o(3291);
      let L = {
        Damage: 'Damage',
        Penetration: 'Penetration',
        'Pierce lvl': 'Pierce Level',
        'Armor Dmg': 'Armor Damage',
        'Vel (m/s)': 'Velocity (m/s)',
        Accuracy: 'Accuracy',
        'V.Recoil Control': 'V.Recoil Control',
        'H.Recoil Control': 'H.Recoil Control',
        'Wound Chance': 'Wound Chance',
        'Extra Range': 'Extra Range',
        'Stamina Drain': 'Stamina Drain',
      };
      var E = (e) => {
          let { ammos: a, caliber: o, tableState: n, setTableState: i } = e;
          if (n.sorting.columnBeingSorted) {
            let e = n.sorting.columnBeingSorted,
              o = n.sorting.direction.highToLow ? -1 : 1;
            console.log(e, o), a.sort((a, r) => (a[e] - r[e]) * o);
          }
          return (0, r.jsxs)(g.xu, {
            bg: 'vulcan.850',
            children: [
              (0, r.jsxs)(P.K, {
                p: '0',
                _focus: {
                  boxShadow: 'none',
                },
                children: [
                  (0, r.jsx)(b.X, {
                    ml: '8px',
                  }),
                  (0, r.jsx)(V.k, {
                    children: (0, r.jsx)(u.x, {
                      zIndex: 100,
                      pl: '8px',
                      fontWeight: 'bold',
                      fontSize: 'xl',
                      children: o,
                    }),
                  }),
                ],
              }),
              (0, r.jsx)(S.H, {
                pt: 1,
                pb: 0,
                px: 0,
                mt: '-34px',
                style: {
                  zIndex: 10,
                },
                children: (0, r.jsxs)(r.Fragment, {
                  children: [
                    (0, r.jsxs)(V.k, {
                      children: [
                        (0, r.jsx)(g.xu, {
                          h: '48px',
                          minW: '175px',
                        }),
                        Object.keys(L).map((e, a) => {
                          let o = L[e];
                          [2, 3, 4, 5].includes(a);
                          let c = '1';
                          return (
                            0 === a && (c = '1.5'),
                            (0, r.jsxs)(
                              C.M,
                              {
                                flex: c,
                                bg: 'vulcan.800',
                                fontWeight: 'semibold',
                                fontSize: '10',
                                textAlign: 'center',
                                children: [
                                  (0, r.jsx)(u.x, {
                                    color: 'tarkovYellow.100',
                                    children: e.toUpperCase(),
                                  }),
                                  a < 5 &&
                                    (0, r.jsxs)(g.xu, {
                                      ml: '4px',
                                      children: [
                                        (0, r.jsx)(j.qwl, {
                                          cursor: 'pointer',
                                          onClick: () => {
                                            i({
                                              ...n,
                                              sorting: {
                                                columnBeingSorted: o,
                                                direction: {
                                                  highToLow: !1,
                                                },
                                              },
                                            });
                                          },
                                        }),
                                        (0, r.jsx)(j.dbR, {
                                          cursor: 'pointer',
                                          onClick: () => {
                                            i({
                                              ...n,
                                              sorting: {
                                                columnBeingSorted: o,
                                                direction: {
                                                  highToLow: !0,
                                                },
                                              },
                                            });
                                          },
                                        }),
                                      ],
                                    }),
                                ],
                              },
                              'header-'.concat(a)
                            )
                          );
                        }),
                      ],
                    }),
                    a.map((e, a) =>
                      (0, r.jsx)(
                        'div',
                        {
                          children: (0, r.jsxs)(V.k, {
                            bg: a % 2 == 0 ? 'vulcan.900' : 'vulcan.850',
                            fontWeight: 'bold',
                            _hover: {
                              bg: 'vulcan.800',
                            },
                            color: 'tarkovYellow.100',
                            fontSize: 12,
                            children: [
                              (0, r.jsxs)(p.U, {
                                minW: '175px',
                                py: '2px',
                                pr: '8px',
                                children: [
                                  (0, r.jsx)(C.M, {
                                    fontSize: 'xs',
                                    fontWeight: 'semibold',
                                    ml: '8px',
                                    children: e.Name.replace(o, ''),
                                  }),
                                  (0, r.jsx)(v.L, {}),
                                ],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1.5',
                                color: 'tarkovYellow.100',
                                children: e.Damage,
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                color: 'tarkovYellow.100',
                                children: e.Penetration,
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                color: 'tarkovYellow.100',
                                children: e['Pierce Level'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                color: 'tarkovYellow.100',
                                children: e['Armor Damage'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                color: 'tarkovYellow.100',
                                children: e['Velocity (m/s)'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                bg: A(e.Accuracy, !1),
                                color: 'black',
                                children: e.Accuracy,
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                bg: A(e['V.Recoil Control'], !1),
                                color: 'black',
                                children: e['V.Recoil Control'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                bg: A(e['H.Recoil Control'], !1),
                                color: 'black',
                                children: e['H.Recoil Control'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                bg: y(e['Wound Chance']),
                                color: 'black',
                                children: e['Wound Chance'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                bg: y(e['Extra Range']),
                                color: 'black',
                                children: e['Extra Range'],
                              }),
                              (0, r.jsx)(C.M, {
                                flex: '1',
                                bg: A(e['Stamina Drain'], !0),
                                color: 'black',
                                children: e['Stamina Drain'],
                              }),
                            ],
                          }),
                        },
                        e.Name
                      )
                    ),
                  ],
                }),
              }),
            ],
          });
        },
        w = o(9289),
        N = (e) => {
          let { ammos: a, caliber: o } = e;
          return (0, r.jsxs)(g.xu, {
            bg: 'vulcan.850',
            children: [
              (0, r.jsxs)(P.K, {
                p: '0',
                _focus: {
                  boxShadow: 'none',
                },
                children: [
                  (0, r.jsx)(b.X, {
                    ml: '8px',
                  }),
                  (0, r.jsx)(V.k, {
                    children: (0, r.jsx)(u.x, {
                      zIndex: 100,
                      pl: '8px',
                      fontWeight: 'bold',
                      fontSize: 'xl',
                      children: o,
                    }),
                  }),
                ],
              }),
              (0, r.jsx)(S.H, {
                pt: 1,
                pb: 0,
                px: 0,
                mt: '-34px',
                style: {
                  zIndex: 10,
                },
                children: (0, r.jsxs)(r.Fragment, {
                  children: [
                    (0, r.jsx)(V.k, {
                      children: (0, r.jsx)(g.xu, {
                        h: '32px',
                      }),
                    }),
                    a.map((e, a) =>
                      (0, r.jsx)(
                        'div',
                        {
                          children: (0, r.jsxs)(
                            g.xu,
                            {
                              bg: 'vulcan.800',
                              mb: '12px',
                              p: '8px',
                              children: [
                                (0, r.jsxs)(p.U, {
                                  children: [
                                    (0, r.jsx)(C.M, {
                                      fontSize: 'sm',
                                      fontWeight: 'semibold',
                                      ml: '8px',
                                      children: e.Name,
                                    }),
                                    (0, r.jsx)(v.L, {}),
                                  ],
                                }),
                                (0, r.jsxs)(p.U, {
                                  mt: '8px',
                                  fontSize: 'xs',
                                  justify: 'space-around',
                                  style: {
                                    whiteSpace: 'nowrap',
                                  },
                                  children: [
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'Damage',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: '#4E4E4C',
                                          w: '100%',
                                          children: e.Damage || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'Penetration',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: '#4E4E4C',
                                          w: '100%',
                                          children: e.Penetration || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'Pierce Lvl',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: '#4E4E4C',
                                          w: '100%',
                                          children: e['Pierce Level'] || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'Armor Dmg',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: '#4E4E4C',
                                          w: '100%',
                                          children: e['Armor Damage'] || '-',
                                        }),
                                      ],
                                    }),
                                  ],
                                }),
                                (0, r.jsxs)(p.U, {
                                  mt: '8px',
                                  fontSize: 'xs',
                                  justify: 'space-around',
                                  style: {
                                    whiteSpace: 'nowrap',
                                  },
                                  children: [
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'Vel (m/s)',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: '#4E4E4C',
                                          w: '100%',
                                          children: e['Velocity (m/s)'] || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'Accuracy',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: A(e.Accuracy, !1),
                                          color: 'black',
                                          w: '100%',
                                          children: e.Accuracy || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'V.Recoil Ctrl',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: A(e['V.Recoil Control'], !1),
                                          color: 'black',
                                          w: '100%',
                                          children:
                                            e['V.Recoil Control'] || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          p: '2px',
                                          w: '100%',
                                          children: 'H.Recoil Ctrl',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: A(e['H.Recoil Control'], !1),
                                          color: 'black',
                                          w: '100%',
                                          children:
                                            e['H.Recoil Control'] || '-',
                                        }),
                                      ],
                                    }),
                                  ],
                                }),
                                (0, r.jsx)(w.i, {
                                  my: '8px',
                                  borderColor: 'vulcan.900',
                                }),
                                (0, r.jsxs)(p.U, {
                                  fontSize: 'xs',
                                  justify: 'space-around',
                                  children: [
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          w: '100%',
                                          p: '1px',
                                          children: 'Wound %',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: y(e['Wound Chance']),
                                          color: 'black',
                                          w: '100%',
                                          children: e['Wound Chance'] || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          w: '100%',
                                          p: '1px',
                                          children: 'Extra Range',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: y(e['Extra Range']),
                                          color: 'black',
                                          w: '100%',
                                          children: e['Extra Range'] || '-',
                                        }),
                                      ],
                                    }),
                                    (0, r.jsxs)(s.g, {
                                      spacing: '0',
                                      w: '100%',
                                      children: [
                                        (0, r.jsx)(C.M, {
                                          bg: '#232314',
                                          w: '100%',
                                          p: '1px',
                                          children: 'Stam Drain',
                                        }),
                                        (0, r.jsx)(C.M, {
                                          bg: A(e['Stamina Drain'], !1),
                                          color: 'black',
                                          w: '100%',
                                          children: e['Stamina Drain'] || '-',
                                        }),
                                      ],
                                    }),
                                  ],
                                }),
                              ],
                            },
                            'allAmmos-'.concat(a)
                          ),
                        },
                        e.Name
                      )
                    ),
                  ],
                }),
              }),
            ],
          });
        };
      function H() {
        let [e, a] = (0, h.useState)(''),
          o = t
            .filter(
              (a) =>
                a.Caliber.toLowerCase().includes(e.toLowerCase()) ||
                a.Name.toLowerCase().includes(e.toLowerCase())
            )
            .reduce(
              (e, a) => (
                e[a.Caliber] || (e[a.Caliber] = []), e[a.Caliber].push(a), e
              ),
              {}
            ),
          n = Object.keys(o),
          [c, A] = (0, h.useState)([...Array(n.length).keys()]),
          y = (0, x.S)({
            base: !0,
            md: !1,
          }),
          [P, b] = (0, h.useState)({
            sorting: {
              columnBeingSorted: null,
              direction: {
                highToLow: !0,
              },
            },
          });
        return (0, r.jsxs)(r.Fragment, {
          children: [
            (0, r.jsxs)(m(), {
              children: [
                (0, r.jsx)('title', {
                  children: 'ABI | Ammo and Armor Charts \uD83D\uDCCA',
                }),
                (0, r.jsx)('link', {
                  rel: 'icon',
                  href: 'https://eft-ammo.b-cdn.net/favicon.ico',
                }),
                (0, r.jsx)('meta', {
                  name: 'description',
                  content:
                    'Arena Breakout: Infinite Ammo and Armor Charts created by Filod \uD83D\uDE4C',
                }),
                (0, r.jsx)('meta', {
                  itemProp: 'name',
                  content:
                    'abi-ammo.com \uD83C\uDFAE | The definitive Arena Breakout: Infinite Ammo charts v0.x',
                }),
                (0, r.jsx)('meta', {
                  itemProp: 'description',
                  content:
                    'Arena Breakout: Infinite Ammo and Armor Charts created by Filod \uD83D\uDE4C',
                }),
                (0, r.jsx)('meta', {
                  property: 'og:url',
                  content: 'https://abi-ammo.com/',
                }),
                (0, r.jsx)('meta', {
                  property: 'og:type',
                  content: 'website',
                }),
                (0, r.jsx)('meta', {
                  property: 'og:title',
                  content:
                    'abi-ammo.com \uD83C\uDFAE | The definitive Arena Breakout: Infinite Ammo charts v0.x',
                }),
                (0, r.jsx)('meta', {
                  property: 'og:description',
                  content:
                    'Arena Breakout: Infinite Ammo and Armor Charts created by Filod \uD83D\uDE4C',
                }),
                (0, r.jsx)('meta', {
                  name: 'twitter:card',
                  content: 'summary_large_image',
                }),
                (0, r.jsx)('meta', {
                  property: 'twitter:domain',
                  content: 'abi-ammo.com',
                }),
                (0, r.jsx)('meta', {
                  property: 'twitter:url',
                  content: 'https://abi-ammo.com/',
                }),
                (0, r.jsx)('meta', {
                  name: 'twitter:title',
                  content:
                    'abi-ammo.com \uD83C\uDFAE | The definitive Arena Breakout: Infinite Ammo charts v0.x',
                }),
                (0, r.jsx)('meta', {
                  name: 'twitter:description',
                  content:
                    'Arena Breakout: Infinite Ammo and Armor Charts created by Filod \uD83D\uDE4C',
                }),
              ],
            }),
            (0, r.jsxs)('main', {
              className: ''.concat(i().className),
              children: [
                (0, r.jsx)(g.xu, {
                  pt: '48px',
                  children: (0, r.jsx)(C.M, {
                    children: (0, r.jsxs)(s.g, {
                      children: [
                        (0, r.jsxs)(u.x, {
                          textAlign: 'center',
                          color: 'tarkovYellow.100',
                          fontWeight: 'bold',
                          mt: '24px',
                          as: 'h1',
                          style: {
                            fontStyle: 'italic',
                          },
                          children: [
                            (0, r.jsx)(u.x, {
                              fontSize: ['xl', '5xl'],
                              children: 'Arena Breakout: Infinite',
                            }),
                            (0, r.jsx)(u.x, {
                              fontSize: ['lg', '4xl'],
                              children: 'Ammo and Armor Charts',
                            }),
                          ],
                        }),
                        (0, r.jsxs)(u.x, {
                          color: 'green.500',
                          fontSize: 'md',
                          textAlign: 'center',
                          fontWeight: 'bold',
                          children: [
                            'Updated on August 13th 2024 | by',
                            ' ',
                            (0, r.jsx)(l.r, {
                              href: 'https://www.eft-ammo.com',
                              isExternal: !0,
                              textDecoration: 'underline',
                              children: 'eft-ammo.com',
                            }),
                          ],
                        }),
                      ],
                    }),
                  }),
                }),
                (0, r.jsx)(C.M, {
                  pt: '48px',
                  pb: '96px',
                  children: (0, r.jsxs)(s.g, {
                    children: [
                      (0, r.jsx)(d.I, {
                        type: 'text',
                        placeholder:
                          'Search by caliber or ammo name... e.g. 39mm or lps',
                        value: e,
                        onChange: (e) => a(e.target.value),
                        maxW: '780px',
                        borderRadius: 'none',
                        bg: 'vulcan.900',
                        color: 'tarkovYellow.100',
                        fontWeight: 'normal',
                        borderColor: 'vulcan.800',
                        _placeholder: {
                          color: 'tarkovYellow.100',
                          textAlign: 'center',
                        },
                        mb: 4,
                      }),
                      (0, r.jsx)(D.U, {
                        textAlign: 'center',
                        defaultIndex: c,
                        index: c,
                        allowMultiple: !0,
                        reduceMotion: !0,
                        onChange: (e) => {
                          A(e);
                        },
                        w: ['100%'],
                        children: (0, r.jsx)(s.g, {
                          children: Object.keys(o).map((e, a) =>
                            (0, r.jsx)(
                              g.xu,
                              {
                                color: 'tarkovYellow.100',
                                mx: '24px',
                                rounded: 'sm',
                                border: '6px solid',
                                borderColor: 'vulcan.900',
                                w: '100%',
                                children: (0, r.jsx)(
                                  R.Q,
                                  {
                                    border: 'none',
                                    w: '100%',
                                    children: y
                                      ? (0, r.jsx)(N, {
                                          ammos: o[e],
                                          caliber: e,
                                        })
                                      : (0, r.jsx)(E, {
                                          tableState: P,
                                          setTableState: b,
                                          ammos: o[e],
                                          caliber: e,
                                        }),
                                  },
                                  e
                                ),
                              },
                              'allAmmos-'.concat(a)
                            )
                          ),
                        }),
                      }),
                    ],
                  }),
                }),
              ],
            }),
          ],
        });
      }
    },
  },
  function (e) {
    e.O(0, [961, 907, 888, 774, 179], function () {
      return e((e.s = 8312));
    }),
      (_N_E = e.O());
  },
]);
